micon.micon.*:
  type: config_entity
  label: 'Micon config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    status:
      type: boolean
      label: 'Status'
    type:
      type: string
      label: 'Type'
    archive:
      type: sequence
      label: 'Archive'
