field.widget.settings.micon_menu:
  type: mapping
  label: 'Link with icon settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    packages:
      type: sequence
      sequence:
        type: boolean
        label: 'Enabled'
