<?php

/**
 * @file
 * Contains micon_link.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function micon_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the micon_link module.
    case 'help.page.micon_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Micon link module provides a widget that allows users to add icons to link fields.') . '</p>';
      return $output;

    default:
  }
}
